<?php
/**
 * Template Name: Privacy Policy
 * The main template file
 *
 * @link https://developer.wordpress.org/themes/basics/template-hierarchy/#single-post
 *
 * @package WordPress
 * @subpackage thirty_two_give
 * @since Thirty Two-Give 1.0
 */

 get_header(); 
?>
<!-- header end -->
 <!-- hero start -->
      <section class="hero-section secondary-bg">
        <div class="container">
          <div class="row">
            <div class="col-12 position-relative z-1 d-flex align-items-center privacy-policy-section">
                <h1
                  class="heading-title text-white big-heading-title text-start"
                >
                  Privacy Policy
                </h1>
            </div>
          </div>
        </div>
      </section>
      <!-- hero end -->
    </div>
      <!-- details section start -->
      <section class="privacy-terms-section section-py">
        <div class="container">
            <div class="row">
                <div class="col-12 mb-3">
                  <p class="fw-400 heading-text-color">Last updated: December 12, 2022</p>
                </div>
                <div class="col-12 privacy-terms-data">
                    <h3 class="fw-600 heading-text-color">General</h3>
                    <p class="fw-400 heading-text-color">This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>
                    <p class="fw-400 heading-text-color">We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.</p>
                    <p class="fw-400 heading-text-color">BY USING OR ACCESSING THE APP, YOU ARE ACCEPTING THE PRACTICES DESCRIBED IN THIS PRIVACY POLICY.</p>
                </div>
                <div class="col-12 privacy-terms-data">
                    <h3 class="fw-600 heading-text-color">Interpretation and Definitions</h3>
                     <h5 class="fw-500 heading-text-color">Interpretation</h5>
                    <p class="fw-400 heading-text-color">The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
                    <h5 class="fw-500 heading-text-color">Definitions</h5>
                    <p class="fw-500 heading-text-color">For the purposes of this Privacy Policy:</p>
                    <p class="fw-400 heading-text-color">Account means a unique account created for You to access our Service or parts of our Service.</p>
                    <p class="fw-400 heading-text-color">Company (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to SEQUENCE AI TECHNOLOGIES, 1041 N DUPONT HWY 1326, DOVER, DE 19901.</p>
                    <p class="fw-400 heading-text-color">Cookies are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.
                      Country refers to: Delaware, United States</p>
                    <p class="fw-400 heading-text-color">Device means any device that can access the Service such as a computer, a cellphone or a digital tablet.</p>
                    <p class="fw-400 heading-text-color">Personal Data is any information that relates to an identified or identifiable individual.</p>
                    <h5 class="fw-500 heading-text-color">Service refers to the Website.</h5>
                    <p class="fw-400 heading-text-color">Service Provider means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</p>
                    <p class="fw-400 heading-text-color">Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit)</p>
                    <p class="fw-400 heading-text-color">Website refers to Fintology, accessible <a href="index.html">www.fintology.io</a> You means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</p>

                </div>
                <div class="col-12 privacy-terms-data">
                    <h3 class="fw-600 heading-text-color">Collecting and Using Your Personal Data</h3>
                    <h5 class="fw-500 heading-text-color">Personal Data</h5>
                    <p class="fw-500 text-black">While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
                    <div class="mb-4">
                        <a href="javascript:void(0)" class="d-block mb-4">Email address</a>
                        <a href="javascript:void(0)" class="d-block mb-4">First name and last name</a>
                        <a href="javascript:void(0)" class="d-block mb-4">Phone number</a>
                        <a href="javascript:void(0)" class="d-block mb-4">Address, State, Province, ZIP/Postal code, City Usage Data</a>
                    </div>
                    <h5 class="fw-500 heading-text-color">Usage Data</h5>
                    <p class="fw-400 heading-text-color">Usage Data is collected automatically when using the Service.</p>
                    <p class="fw-400 heading-text-color">Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
                    <p class="fw-400 heading-text-color">When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.</p>
                    <p class="fw-400 heading-text-color">We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.</p>
                  </div>
                <div class="col-12 privacy-terms-data">
                    <h3 class="fw-600 heading-text-color">Tracking Technologies and Cookies</h3>
                    <p class="fw-500 text-black">We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:</p>
                    <ul class="li-list-style-dot">
                      <li class="fw-400 heading-text-color">Cookies or Browser Cookies. A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies.</li>
                      <li class="fw-400 heading-text-color">Web Beacons. Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of a certain section and verifying system and server integrity).</li>
                  </ul>
                  <p class="fw-400 heading-text-color">Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser. Learn more about cookies on the Privacy Policies website article.</p>
                  <p class="fw-500 text-black">We use both Session and Persistent Cookies for the purposes set out below:</p>
                  <h5 class="fw-500 heading-text-color">Necessary / Essential Cookies</h5>
                  <a href="javascript:void(0)" class="d-block mb-4">Type: <span class="text-black">Session Cookies</span></a>
                  <a href="javascript:void(0)" class="d-block mb-4">Administered by: <span class="text-black">Us</span></a>
                  <a href="javascript:void(0)" class="d-block mb-4">Purpose: <span class="text-black">These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services.</span></a>
                  <h5 class="fw-500 heading-text-color">Functionality Cookies</h5>
                  <a href="javascript:void(0)" class="d-block mb-4">Type: <span class="text-black">Persistent Cookies</span></a>
                  <a href="javascript:void(0)" class="d-block mb-4">Administered by: <span class="text-black">Us</span></a>
                  <a href="javascript:void(0)" class="d-block mb-4">Purpose: <span class="text-black">These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website.</span></a>
                  <p class="fw-400 heading-text-color">For more information about the cookies we use and your choices regarding cookies, please visit our Cookies Policy or the Cookies section of our Privacy Policy.</p>
                </div>
                <div class="col-12 privacy-terms-data">
                    <h3 class="fw-600 heading-text-color">Use of Your Personal Data</h3>
                    <p class="fw-500 text-black">The Company may use Personal Data for the following purposes:</p>
                    <p class="fw-400 heading-text-color">To provide and maintain our Service, including to monitor the usage of our Service.</p>
                    <p class="fw-400 heading-text-color">To manage Your Account: to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.For the performance of a contract: the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.</p>
                    <p class="fw-400 heading-text-color">To contact You: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.</p>
                    <p class="fw-400 heading-text-color">To provide You with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.</p>
                    <p class="fw-400 heading-text-color">To manage Your requests: To attend and manage Your requests to Us.For business transfers: We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred.</p>
                    <p class="fw-400 heading-text-color">For other purposes: We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.</p>
                    <p class="fw-500 text-black">We may share Your personal information in the following situations:</p>
                    <ul class="li-list-style-dot">
                      <li class="fw-400 heading-text-color">With Service Providers: We may share Your personal information with Service Providers to monitor and analyze the use of our Service, for payment processing, to contact You.</li>
                      <li class="fw-400 heading-text-color">For business transfers: We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company.</li>
                      <li class="fw-400 heading-text-color">With Affiliates: We may share Your information with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners or other companies that We control or that are under common control with Us.</li>
                      <li class="fw-400 heading-text-color">With business partners: We may share Your information with Our business partners to offer You certain products, services or promotions.</li>
                      <li class="fw-400 heading-text-color">With other users: when You share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside.</li>
                      <li class="fw-400 heading-text-color">With Your consent: We may disclose Your personal information for any other purpose with Your consent.</li>
                  </ul>
                </div>
                <div class="col-12 privacy-terms-data">
                    <h3 class="fw-600 heading-text-color">Retention of Your Personal Data</h3>
                    <p class="fw-400 heading-text-color">The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.</p>
                    <p class="fw-400 heading-text-color">Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.</p>
                    <p class="fw-400 heading-text-color">The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.</p>
                  </div>
                <div class="col-12 privacy-terms-data">
                    <h3 class="fw-600 heading-text-color">Delete Your Personal Data</h3>
                    <p class="fw-400 heading-text-color">You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.</p>
                    <p class="fw-400 heading-text-color">Our Service may give You the ability to delete certain information about You from within the Service.</p>
                    <p class="fw-400 heading-text-color">You may update, amend, or delete Your information at any time by signing in to Your Account, if you have one, and visiting the account settings section that allows you to manage Your personal information. You may also contact Us to request access to, correct, or delete any personal information that You have provided to Us.</p>
                    <p class="fw-400 heading-text-color text-uppercase">Please note, however, that We may need to retain certain information when we have a legal obligation or lawful basis to do so.</p>
                </div>
                <div class="col-12 privacy-terms-data">
                    <h3 class="fw-600 heading-text-color">Disclosure of Your Personal Data</h3>
                    <h5 class="fw-500 heading-text-color">Business Transactions</h5>
                    <p class="fw-400 heading-text-color">If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.</p>
                    <h5 class="fw-500 heading-text-color">Law enforcement</h5>
                    <p class="fw-400 heading-text-color text-capitalize">Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).</p>
                    <h5 class="fw-500 heading-text-color">Other legal requirements</h5>
                    <p class="fw-400 heading-text-color text-capitalize">The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:</p>
                    <ul class="li-list-style-dot">
                      <li class="fw-400 heading-text-color">Comply with a legal obligation</li>
                      <li class="fw-400 heading-text-color">Protect and defend the rights or property of the Company</li>
                      <li class="fw-400 heading-text-color">Prevent or investigate possible wrongdoing in connection with the Service</li>
                      <li class="fw-400 heading-text-color">Protect the personal safety of Users of the Service or the public</li>
                      <li class="fw-400 heading-text-color">Protect against legal liability</li>
                  </ul>
                  </div>
                <div class="col-12 privacy-terms-data">
                    <h3 class="fw-600 heading-text-color">Security of Your Personal Data</h3>
                    <p class="fw-400 heading-text-color">The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.</p>
                    <h5 class="fw-500 heading-text-color">Detailed Information on the Processing of Your Personal Data</h5>
                    <p class="fw-400 heading-text-color">The Service Providers We use may have access to Your Personal Data. These third-party vendors collect, store, use, process and transfer information about Your activity on Our Service in accordance with their Privacy Policies.</p>
                    <h5 class="fw-500 heading-text-color">Payments</h5>
                    <p class="fw-400 heading-text-color">We may provide paid products and/or services within the Service. In that case, we may use third-party services for payment processing (e.g. payment processors).</p>
                    <p class="fw-400 heading-text-color">We will not store or collect Your payment card details. That information is provided directly to Our third-party payment processors whose use of Your personal information is governed by their Privacy Policy. These payment processors adhere to the standards set by PCI-DSS as managed by the PCI Security Standards Council, which is a joint effort of brands like Visa, Mastercard, American Express and Discover. PCI-DSS requirements help ensure the secure handling of payment information.</p>
                  </div>
                <div class="col-12 privacy-terms-data">
                    <h3 class="fw-600 heading-text-color">Stripe</h3>
                    <p class="fw-400 heading-text-color">Their Privacy Policy can be viewed at <a href="https://stripe.com/us/privacy">https://stripe.com/us/privacy</a></p>
                </div>
                <div class="col-12 privacy-terms-data">
                    <h3 class="fw-600 heading-text-color">Children's Privacy</h3>
                    <p class="fw-400 heading-text-color">Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.</p>
                    <p class="fw-400 heading-text-color">If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent's consent before We collect and use that information.</p>
                </div>
                <div class="col-12 privacy-terms-data">
                    <h3 class="fw-600 heading-text-color">Links to Other Websites</h3>
                    <p class="fw-400 heading-text-color">Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.</p>
                    <p class="fw-400 heading-text-color">We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>
                  </div>
                <div class="col-12 privacy-terms-data">
                    <h3 class="fw-600 heading-text-color">Changes to this Privacy Policy</h3>
                    <p class="fw-400 heading-text-color">We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.</p>
                    <p class="fw-400 heading-text-color">We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy.</p>
                    <p class="fw-400 heading-text-color">You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>
                  </div>
                <div class="col-12 privacy-terms-data">
                    <h3 class="fw-600 heading-text-color">Contact Us</h3>
                    <p class="fw-500 text-black">If you have any questions about this Privacy Policy, You can contact us:</p>
                    <div class="d-sm-flex contact-details-wrap">
                        <span class="fw-600 location-text">Fintology</span>
                        <div class="contact-us-details-wrap ps-sm-5 mt-3 mt-sm-0">
                            <ul>
                              <li>
                                  <a href="mailto:info@fintology.io" class="d-flex align-items-center hover-text">
                                    <svg width="18" height="17" viewBox="0 0 18 17" fill="none" xmlns="http://www.w3.org/2000/svg">
                                      <path d="M0.9 0H17.1C17.3387 0 17.5676 0.0948211 17.7364 0.263604C17.9052 0.432387 18 0.661305 18 0.9V15.3C18 15.5387 17.9052 15.7676 17.7364 15.9364C17.5676 16.1052 17.3387 16.2 17.1 16.2H0.9C0.661305 16.2 0.432387 16.1052 0.263604 15.9364C0.0948211 15.7676 0 15.5387 0 15.3V0.9C0 0.661305 0.0948211 0.432387 0.263604 0.263604C0.432387 0.0948211 0.661305 0 0.9 0ZM9.054 7.8147L3.2832 2.9142L2.1177 4.2858L9.0657 10.1853L15.8886 4.2813L14.7114 2.9196L9.0549 7.8147H9.054Z" fill="#42E26F"/>
                                      </svg>
                                                                             
                                      <span>info@fintology.io</span>
                                  </a>
                              </li>
                                <li>
                                    <a href="<?php echo get_site_url(); ?>" class="d-flex align-items-center hover-text">
                                      <svg width="18" height="18" viewBox="0 0 18 18" fill="none" xmlns="http://www.w3.org/2000/svg">
                                        <path d="M12.2328 5.42605C11.5998 2.486 10.2498 0.625977 9.00118 0.625977C7.75256 0.625977 6.40254 2.486 5.76953 5.42605H12.2328Z" fill="#42E26F"/>
                                        <path d="M5.40039 9.02601C5.40024 9.8287 5.45376 10.6305 5.56059 11.426H12.4403C12.5471 10.6305 12.6006 9.8287 12.6005 9.02601C12.6006 8.22332 12.5471 7.42152 12.4403 6.62598H5.56059C5.45376 7.42152 5.40024 8.22332 5.40039 9.02601Z" fill="#42E26F"/>
                                        <path d="M5.76953 12.626C6.40254 15.566 7.75256 17.426 9.00118 17.426C10.2498 17.426 11.5998 15.566 12.2328 12.626H5.76953Z" fill="#42E26F"/>
                                        <path d="M13.4601 5.42568H17.2402C16.6722 4.13312 15.8093 2.99165 14.7205 2.09283C13.6317 1.19401 12.3474 0.56286 10.9707 0.25C12.1089 1.25141 13.0017 3.10304 13.4601 5.42568Z" fill="#42E26F"/>
                                        <path d="M17.673 6.62598H13.6529C13.7519 7.42215 13.8014 8.22371 13.8011 9.02601C13.8012 9.82833 13.7515 10.6299 13.6523 11.426H17.6724C18.11 9.85594 18.1106 8.19608 17.673 6.62598Z" fill="#42E26F"/>
                                        <path d="M10.9707 17.8017C12.3477 17.489 13.6322 16.8579 14.7212 15.9591C15.8102 15.0602 16.6733 13.9187 17.2414 12.626H13.4613C13.0017 14.9486 12.1089 16.8002 10.9707 17.8017Z" fill="#42E26F"/>
                                        <path d="M4.53982 12.626H0.759766C1.32785 13.9187 2.19101 15.0602 3.28 15.9591C4.369 16.8579 5.6535 17.489 7.03046 17.8017C5.89104 16.8002 4.99823 14.9486 4.53982 12.626Z" fill="#42E26F"/>
                                        <path d="M7.02851 0.25C5.65155 0.56269 4.36704 1.19376 3.27805 2.09259C2.18906 2.99142 1.3259 4.13298 0.757812 5.42568H4.53787C4.99748 3.10304 5.89029 1.25141 7.02851 0.25Z" fill="#42E26F"/>
                                        <path d="M4.19943 9.02601C4.19936 8.22369 4.24905 7.42214 4.34824 6.62598H0.328176C-0.109392 8.19608 -0.109392 9.85594 0.328176 11.426H4.34824C4.24905 10.6299 4.19936 9.82833 4.19943 9.02601Z" fill="#42E26F"/>
                                        </svg>
                                                                               
                                        <span>www.fintology.io</span>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- details section end -->
<?php get_footer(); ?>